### ISSUE TITLE
Move project to at-import organization?

### ISSUE THREAD

**Issue by JohnAlbin** [JohnAlbin/sassy-test#6]
@codingdesigner, @iamcarrico, @metaskills, @scottkellum, @Snugug

I used https://github.com/at-import/navigator for many projects until I switched to Node.js and mocha.

This project, sassy-test, is the Node.js helper utility I wrote to replace navigator. It is based on node-sass's test suite, You point a test at a particular fixture directory and sassy-test compares the rendered input.scss to the given output.css.

Best of all, sassy-test will catch Sass warnings **and errors** and allow you to write tests that _expect_ node-sass to fail.

It supports traditional nodeback-style callbacks or Promises! The promises version is my preference; see https://github.com/JohnAlbin/sassy-test#javascript-promises for an example.

Is the @at-import organization interested in adding this project and adding me?

Thanks,
  John

**Comment by Snugug** [comment]
Yah, absolutely! I've made you a member of **@at-import** and you should be able to move it in yourself now!

**Comment by JohnAlbin** [comment]
Sweet! I'll have to update all the project URLs to point at the new location and figure out how/if I need to update the npm registration.

I wonder if I'll have time to do it before Drupalcon? :-p

**Comment by JohnAlbin** [comment]
@Snugug @iamcarrico Huh. It wouldn't let me transfer ownership because I don't have admin rights to at-import.

Here's the screenshot when I try to transfer ownership:
![screen shot 2016-05-02 at 09 20 42](https://cloud.githubusercontent.com/assets/33429/14945607/39a4ab5a-1047-11e6-96e6-bef691e2f343.png)

![screen shot 2016-05-02 at 08 56 01](https://cloud.githubusercontent.com/assets/33429/14945448/f98515a8-1043-11e6-9c4b-caea2db60006.png)

**Comment by Snugug** [comment]
Hrmm… make me an owner of this repo and I'll move it?

**Comment by Snugug** [comment]
(sorry for the late reply… this has been a… busy few weeks)
